// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $api_slack_commands from "./routes/api/slack-commands.ts";
import * as $api_slack_interactive from "./routes/api/slack-interactive.ts";
import * as $api_slack_webhook from "./routes/api/slack-webhook.ts";
import * as $api_tasks from "./routes/api/tasks.ts";
import * as $index from "./routes/index.tsx";
import * as $slack_test from "./routes/slack-test.tsx";
import * as $TaskManager from "./islands/TaskManager.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/api/slack-commands.ts": $api_slack_commands,
    "./routes/api/slack-interactive.ts": $api_slack_interactive,
    "./routes/api/slack-webhook.ts": $api_slack_webhook,
    "./routes/api/tasks.ts": $api_tasks,
    "./routes/index.tsx": $index,
    "./routes/slack-test.tsx": $slack_test,
  },
  islands: {
    "./islands/TaskManager.tsx": $TaskManager,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
